### PR TITLE
Avoid crashes, some refactoring by swiftlint rules.

### PR DESCRIPTION
**Pull request by alexanderkhitev**
some refactoring

### CODE REVIEW

**Comment by piemonte** [comment]
hey @alexanderkhitev thanks for the project interest and the PR!

these changes are very good. some i'm not sure the reason for changing, so will probably cherry-pick parts. adding an error to the completion handler is also nice.

**Comment by alexanderkhitev** [comment]
Hi @piemonte ! Thanks! If there are any questions, please ask.

**Comment by piemonte** [comment]
hey @alexanderkhitev thanks for the PR. i manually pulled in a couple changes you had made and left a few others.

c5de4b1c3fd1804685cc19df15db5f4c3ed51a88
cd9c352a3ce9c82f886ce26f2cb5386220a0af50

**Comment by alexanderkhitev** [comment]
Hey @piemonte ! Thank you!

**Pull request closed without merging**
