### PR TITLE
Convert dispatch semaphore to group

### PR DESCRIPTION
**Pull request by bojanstef**

### CODE REVIEW

**Comment by bojanstef** [comment]
@piemonte please review when you have a minute. This fix is similar to https://github.com/NextLevel/NextLevelSessionExporter/pull/44 in the sense that the priority inversion is resolved but the functionality remains the same.

**Comment by acushway** [comment]
Hi. I tried including this update in one of my apps that had been having some issues where a video would save and the file was fine but I couldn't then save that video file to the camera roll. It seemed like the file was somehow locked and updating to this code seemed to fix the problem.

However when I shipped the change the crash rate jumped and I can't make much of the stack trace other than it seems to do with the dispatch group and there is an entry in the crash keys:

crash_info_entry_0 | BUG IN CLIENT OF LIBDISPATCH: Unbalanced call to dispatch_group_leave()

I've not seen this personally but it seems to be happening to some users multiple times. This is happening on iPhone, iPad and on iOS 15/16/17

I'll look into it but just raising this for now.

**Comment by acushway** [comment]
Quick update. Seems to be happening for time lapse videos (no audio).

**Comment by acushway** [comment]
I've had a look at the code:

Line 291 and line 303 (dispatchGroup.leave()) should be removed. They allow for leaving a dispatchGroup before it has been entered.

Timelapse videos will now save again in my app.

**Comment by bojanstef** [comment]
Want me to add a PR or will you? @acushway

**Comment by acushway** [comment]
If you could do it that would be great. I've worked by myself for the past 10 years and have no clue what I'm doing as far as git goes :)

**Pull request merged**
